const FETCH_DATA = 'FETCH_DATA'
const FETCH_DATA_RECURRING = 'FETCH_DATA_RECURRING'
const FETCH_DATA_CANCEL = 'FETCH_DATA_CANCEL'
const FETCH_DATA_CANCELLED = 'FETCH_DATA_CANCELLED'
const FETCH_DATA_LATEST = 'FETCH_DATA_LATEST'
const FETCH_REQUEST = 'FETCH_REQUEST'
const FETCH_SUCCESS = 'FETCH_SUCCESS'
const FETCH_FAIL = 'FETCH_FAIL'
const FETCH_RETRY_FAIL = 'FETCH_RETRY_FAIL'
const STORE_FETCH_RESULT = 'STORE_FETCH_RESULT'

export function createAction(type, payload) {	
	return Object.assign({}, {type}, payload)
}

export default { FETCH_DATA, FETCH_DATA_RECURRING, FETCH_DATA_CANCEL, FETCH_DATA_CANCELLED, FETCH_DATA_LATEST,
	FETCH_REQUEST, FETCH_SUCCESS, FETCH_FAIL, FETCH_RETRY_FAIL, STORE_FETCH_RESULT }