const FETCH_DATA = 'FETCH_DATA'
const FETCH_DATA_RECURRING = 'FETCH_DATA_RECURRING'
const FETCH_DATA_CANCEL = 'FETCH_DATA_CANCEL'
const FETCH_DATA_CANCELLED = 'FETCH_DATA_CANCELLED'
const FETCH_DATA_LATEST = 'FETCH_DATA_LATEST'

export function createAction(type, payload) {	
	return Object.assign({}, {type}, payload)
}

export default { FETCH_DATA, FETCH_DATA_RECURRING, FETCH_DATA_CANCEL, FETCH_DATA_CANCELLED, FETCH_DATA_LATEST }