import { merge } from 'lodash'

// App-level request
const DATA_REQUESTED = 'application/DATA_REQUESTED'
const PERIODIC_DATA_REQUESTED = 'application/PERIODIC_DATA_REQUESTED'
const PERIODIC_TERMINATION_REQUESTED = 'application/PERIODIC_TERMINATION_REQUESTED'
const DATA_REQUESTED_USE_LATEST = 'application/DATA_REQUESTED_USE_LATEST'

// System responses
const PERIODIC_TERMINATION_SUCCEEDED = 'sagas/PERIODIC_TERMINATION_SUCCEEDED'

// System requests for fetching/updating
const FETCH_REQUESTED = 'net/FETCH_REQUESTED'
const TRANSIENT_FETCH_REQUESTED = 'net/TRANSIENT_FETCH_REQUESTED'
const KEY_REMOVAL_REQUESTED = 'net/KEY_REMOVAL_REQUESTED'

// System responses to fetch requests
const FETCH_RESULT_RECEIVED = 'net/FETCH_RESULT_RECEIVED'
const FETCH_FAILED = 'net/FETCH_FAILED'
const TRANSIENT_FETCH_RESULT_RECEIVED = 'net/TRANSIENT_FETCH_RESULT_RECEIVED'
const TRANSIENT_FETCH_FAILED = 'net/TRANSIENT_FETCH_FAILED'
const TRY_FETCH_FAILED = 'net/TRY_FETCH_FAILED'

export function createAction(type: string, payload: any) {
	return merge({}, { type }, payload)
}

export default {
	DATA_REQUESTED,
	PERIODIC_DATA_REQUESTED,
	PERIODIC_TERMINATION_REQUESTED,
	DATA_REQUESTED_USE_LATEST,
	PERIODIC_TERMINATION_SUCCEEDED,
	FETCH_REQUESTED,
	TRANSIENT_FETCH_REQUESTED,
	KEY_REMOVAL_REQUESTED,
	FETCH_RESULT_RECEIVED,
	FETCH_FAILED,
	TRANSIENT_FETCH_RESULT_RECEIVED,
	TRANSIENT_FETCH_FAILED,
	TRY_FETCH_FAILED,
}
